/*
 * Moderne Proprietary. Only for use by Moderne customers under the terms of a commercial contract.
 */

package recipes

import (
	"github.com/moderneinc/recipes-go/recipes/errorhandling"
	"github.com/moderneinc/recipes-go/recipes/migration"
	"github.com/moderneinc/recipes-go/recipes/migration/jsonv2"
	"github.com/moderneinc/recipes-go/recipes/migration/testify"
	"github.com/moderneinc/recipes-go/recipes/naming"
	"github.com/moderneinc/recipes-go/recipes/performance"
	"github.com/moderneinc/recipes-go/recipes/redundancy"
	"github.com/moderneinc/recipes-go/recipes/simplification"
	"github.com/moderneinc/recipes-go/recipes/style"
	"github.com/openrewrite/rewrite/rewrite-go/pkg/recipe"
)

// Activate registers all Go code quality recipes with the given registry.
func Activate(r *recipe.Registry) {
	// Matches rewrite-go's go-categories.yml so these merge into the one Go category.
	golang := recipe.CategoryDescriptor{
		DisplayName: "Go",
		Description: "Recipes for the [Go](https://go.dev/) programming language.",
	}
	codeQuality := recipe.CategoryDescriptor{DisplayName: "Code quality", Description: "Recipes for improving Go code quality"}
	simplify := recipe.CategoryDescriptor{DisplayName: "Simplification", Description: "Simplify expressions and patterns"}
	redundant := recipe.CategoryDescriptor{DisplayName: "Redundancy", Description: "Remove redundant code"}

	// Simplification
	r.Register(&simplification.SimplifyBooleanExpression{}, golang, codeQuality, simplify)
	r.Register(&simplification.ReplaceTimeSinceWithSince{}, golang, codeQuality, simplify)
	r.Register(&simplification.ReplaceTimeUntilWithUntil{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyRedundantNilCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifySliceRange{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyFmtSprintf{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferBytesEqual{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferSortInts{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsHasPrefix{}, golang, codeQuality, simplify)
	r.Register(&simplification.UseStringsReplaceAll{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyRedundantTrimSpace{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsContainsOverCount{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferEmptyStringCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferLenCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferIoDiscard{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferIoNopCloser{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferIoReadAll{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsReadFile{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsWriteFile{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsMkdirTemp{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsCreateTemp{}, golang, codeQuality, simplify)
	r.Register(&simplification.AvoidChannelLenCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.RemoveRedundantRangeBlank{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifySingleCaseSelect{}, golang, codeQuality, simplify)
	r.Register(&simplification.UseStructuredLogging{}, golang, codeQuality, simplify)
	r.Register(&simplification.RemoveSwitchTrueTag{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferBytesHasPrefix{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferCopyString{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferErrorsIsForOsCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferErrorsIsForPermission{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferFilepathClean{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferIoWriteString{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsReadDir{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferSlicesSort{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStrconvAtoi{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsBuilderWriteString{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsNewReader{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyTrimLeftNoop{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifySprintfConcat{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyDoubleNegation{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyBytesBufferRoundtrip{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyBytesSplitN{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyRedundantBytesTrimSpace{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifySplitN{}, golang, codeQuality, simplify)
	r.Register(&simplification.UseBytesReplaceAll{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferBytesContainsAny{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsContainsAny{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsContainsRune{}, golang, codeQuality, simplify)
	r.Register(&simplification.UseHttpNewRequestWithContext{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsIsTimeout{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyErrorsIsNil{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferMinMaxBuiltin{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferBytesContainsRune{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyBytesEqualNil{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyIfReturnBool{}, golang, codeQuality, simplify)
	r.Register(&simplification.MergeCollapsibleIf{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyRedundantLogicalExpression{}, golang, codeQuality, simplify)
	r.Register(&simplification.MergeIdenticalBranches{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringComparison{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsToLowerMap{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsToUpperMap{}, golang, codeQuality, simplify)

	// Redundancy
	r.Register(&redundancy.RemoveRedundantReturn{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantBreak{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantBreakInSelect{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantSprintf{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantTypeConversion{}, golang, codeQuality, redundant)
	r.Register(&redundancy.UseDocumentedBlankImport{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveEmptyDefault{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveEmptySwitch{}, golang, codeQuality, redundant)
	r.Register(&redundancy.SimplifyNilCheckBeforeClose{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantElse{}, golang, codeQuality, redundant)
	r.Register(&redundancy.SimplifyRedundantLenBeforeRange{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveSelfAssignment{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveUnreachableCode{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveConstantCondition{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveEmptyLoop{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindEmptyFmtSprintf{}, golang, codeQuality, redundant)
	r.Register(&redundancy.SimplifyGoroutineClosure{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantInterfaceAssertion{}, golang, codeQuality, redundant)
	r.Register(&redundancy.UseMeaningfulReturnValues{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveDoubleDeref{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveDuplicateConditions{}, golang, codeQuality, redundant)
	r.Register(&redundancy.AllBranchesIdentical{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveUnconditionalValueOverwrite{}, golang, codeQuality, redundant)

	// Style
	styleCategory := recipe.CategoryDescriptor{DisplayName: "Style", Description: "Code style and conventions"}
	r.Register(&style.UseErrorsNewForSimpleErrors{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferStringsContains{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferBytesContains{}, golang, codeQuality, styleCategory)
	r.Register(&style.AddExportedFuncComment{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferStringsEqualFold{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferStringsEqualFoldSingle{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferRegexpMustCompile{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidInitFunction{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidGlobalVariable{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferRawStringForRegex{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseCryptoRand{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseStrongHash{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidDotImport{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferHexEncoding{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferStrconvQuote{}, golang, codeQuality, styleCategory)
	r.Register(&style.WrapErrorBeforeReturn{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditChannelClose{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditContextBackground{}, golang, codeQuality, styleCategory)
	r.Register(&style.ResolveContextTodo{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidContextWithValue{}, golang, codeQuality, styleCategory)
	r.Register(&style.ReduceNestingDepth{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindDeprecatedAtomicFunctions{}, golang, codeQuality, styleCategory)
	r.Register(&style.RemoveEmptyFunction{}, golang, codeQuality, styleCategory)
	r.Register(&style.RemoveEmptyGoroutine{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidEmptyInterfaceParam{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditExecCommand{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditBindAllInterfaces{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditGoroutineClosure{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidHardcodedCredentials{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseCustomHttpClient{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseHttpServerWithTimeout{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditHttpRedirect{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseTlsForHttp{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditJsonNumber{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditJsonRawMessage{}, golang, codeQuality, styleCategory)
	r.Register(&style.KeepInterfacesSmall{}, golang, codeQuality, styleCategory)
	r.Register(&style.KeepFunctionsShort{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseNamedConstant{}, golang, codeQuality, styleCategory)
	r.Register(&style.LimitFunctionParameters{}, golang, codeQuality, styleCategory)
	r.Register(&style.LimitReturnValues{}, golang, codeQuality, styleCategory)
	r.Register(&style.ReduceErrorCheckNesting{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnsureFileClosed{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseSkipWithReason{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidSqlStringConcat{}, golang, codeQuality, styleCategory)
	r.Register(&style.CheckTemplateExecuteError{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditTestFatal{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditTestMain{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidTimeSleep{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseCommaOkTypeAssertion{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseBufferedChannel{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidUnsafePackage{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferMakeForEmptyMap{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnsureSqlConnectionClosed{}, golang, codeQuality, styleCategory)
	r.Register(&style.AuditYamlUnmarshal{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidFormatStringVariable{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindMapRangeClear{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidNestedGoroutine{}, golang, codeQuality, styleCategory)
	r.Register(&style.RemoveDebugPrint{}, golang, codeQuality, styleCategory)
	r.Register(&style.SimplifySelectDefaultOnly{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidGoto{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidLabel{}, golang, codeQuality, styleCategory)
	r.Register(&style.SimplifyComplexSwitch{}, golang, codeQuality, styleCategory)
	r.Register(&style.RemoveDeprecatedRandSeed{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnforceTlsVerification{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseParameterizedSqlQuery{}, golang, codeQuality, styleCategory)
	r.Register(&style.UseRestrictiveFilePermissions{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnsurePreparedStatementClosed{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnsureTransactionFinalized{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnsureTempCleanedUp{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnsureTickerStopped{}, golang, codeQuality, styleCategory)
	r.Register(&style.AvoidFallthrough{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnsureHttpBodyClosed{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnsureSqlRowsClosed{}, golang, codeQuality, styleCategory)
	r.Register(&style.EnsureTimerStopped{}, golang, codeQuality, styleCategory)

	// Error handling
	errCategory := recipe.CategoryDescriptor{DisplayName: "Error handling", Description: "Error handling best practices"}
	r.Register(&errorhandling.PreferErrorsIsOverEquality{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.HandleErrorReturn{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.WrapErrorWithContext{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.AvoidPanic{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.HandleCheckedError{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.CheckCloseError{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.HandleDeferredCloseError{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.UseErrorsIsOverStringComparison{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.UseErrorsAs{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.AvoidLogFatal{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.AuditErrorStringFormat{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FixErrorStringFormat{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.AuditMultipleErrorWraps{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.AvoidOsExit{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.AuditRecover{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorfWrapVerb{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.SimplifyRedundantErrorWrap{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.UsePackageLevelErrorSentinel{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsContext{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsEOF{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsForFieldAccess{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsSqlNoRows{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsHttpServerClosed{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsNetClosed{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsOsInvalid{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.UseErrorMethod{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.CheckContextError{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.AuditMustFunction{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.HandleSwallowedError{}, golang, codeQuality, errCategory)

	// Performance
	perfCategory := recipe.CategoryDescriptor{DisplayName: "Performance", Description: "Performance optimizations"}
	r.Register(&performance.PreallocateSlice{}, golang, codeQuality, perfCategory)
	r.Register(&performance.PreferStrconvItoa{}, golang, codeQuality, perfCategory)
	r.Register(&performance.PreferStrconvFormatBool{}, golang, codeQuality, perfCategory)
	r.Register(&performance.AvoidDeferInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.ReuseJsonCodecInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.AllocateMapOutsideLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.AllocateOutsideLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.AvoidReflection{}, golang, codeQuality, perfCategory)
	r.Register(&performance.CompileRegexOutsideLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.UseStringsBuilderInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.PreferBytesBufferString{}, golang, codeQuality, perfCategory)
	r.Register(&performance.SimplifySprintfChar{}, golang, codeQuality, perfCategory)
	r.Register(&performance.CreateChannelOutsideLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.AvoidFmtInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.LimitGoroutinesInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.AvoidLockInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.AvoidReadAllInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.BatchHttpCalls{}, golang, codeQuality, perfCategory)
	r.Register(&performance.OpenFileOutsideLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.OptimizeCopyInLoop{}, golang, codeQuality, perfCategory)

	// Naming
	namingCategory := recipe.CategoryDescriptor{DisplayName: "Naming", Description: "Naming conventions"}
	r.Register(&naming.UseErrPrefixForErrors{}, golang, codeQuality, namingCategory)
	r.Register(&naming.RemovePackagePrefixFromName{}, golang, codeQuality, namingCategory)
	r.Register(&naming.UseMixedCaps{}, golang, codeQuality, namingCategory)
	r.Register(&naming.UseMixedCapsForConstants{}, golang, codeQuality, namingCategory)
	r.Register(&naming.UseCtxForContextParam{}, golang, codeQuality, namingCategory)
	r.Register(&naming.RemoveGetterPrefix{}, golang, codeQuality, namingCategory)
	r.Register(&naming.UseShortReceiverName{}, golang, codeQuality, namingCategory)
	r.Register(&naming.UseDescriptiveVarNames{}, golang, codeQuality, namingCategory)
	r.Register(&naming.UseDescriptivePackageName{}, golang, codeQuality, namingCategory)

	// Migration
	migrationCategory := recipe.CategoryDescriptor{DisplayName: "Migration", Description: "Migrate to newer Go versions"}
	r.Register(&migration.ChangeGoVersion{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.UpgradeGoTo118{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.UpgradeGoTo119{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.UpgradeGoTo120{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.UpgradeGoTo121{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.UpgradeGoTo122{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.UpgradeGoTo123{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.UpgradeGoTo124{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.UpgradeGoTo125{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.UpgradeGoTo126{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.GoModTidy{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.AddMissingGoModRequires{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.RemoveUnusedGoModRequires{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.FixGoModIndirectMarkers{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.FormatGoMod{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.FindMissingGoModRequires{}, golang, codeQuality, migrationCategory)
	r.Register(&migration.FindUnusedGoModRequires{}, golang, codeQuality, migrationCategory)

	// Migration — adopt stretchr/testify
	testifyCategory := recipe.CategoryDescriptor{DisplayName: "Testify", Description: "Adopt the stretchr/testify assertion library"}
	r.Register(&testify.AdoptTestify{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyRequireNoError{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyAssertNoError{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyRequireError{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyAssertError{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyRequireEqual{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyAssertEqual{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyRequireTrue{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyAssertTrue{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyRequireNil{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyAssertNil{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyRequireLen{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AdoptTestifyAssertLen{}, golang, codeQuality, migrationCategory, testifyCategory)
	r.Register(&testify.AddTestifyDependency{}, golang, codeQuality, migrationCategory, testifyCategory)

	// Migration — encoding/json to encoding/json/v2
	jsonV2Category := recipe.CategoryDescriptor{DisplayName: "JSON v2", Description: "Migrate encoding/json to encoding/json/v2"}
	r.Register(&jsonv2.FindEncodingJsonUsage{}, golang, codeQuality, migrationCategory, jsonV2Category)
	r.Register(&jsonv2.MigrateToJSONV2{}, golang, codeQuality, migrationCategory, jsonV2Category)
	r.Register(&jsonv2.MigrateToJSONV2PreservingV1{}, golang, codeQuality, migrationCategory, jsonV2Category)
	r.Register(&jsonv2.PreserveV1Semantics{}, golang, codeQuality, migrationCategory, jsonV2Category)
	r.Register(&jsonv2.AddV1FormatTags{}, golang, codeQuality, migrationCategory, jsonV2Category)
}
