// Code generated by goexportdata. DO NOT EDIT.

package otelexportdata

import (
	"embed"
	"io/fs"
)

//go:embed all:blobs
var blobs embed.FS

// FS holds the export data for Paths, ready to hand to a template's
// ExportData option.
var FS, _ = fs.Sub(blobs, "blobs")

// Paths are the import paths FS covers, for exportdata.Verify to check.
var Paths = []string{
	"go.opentelemetry.io/otel",
	"go.opentelemetry.io/otel/metric",
	"go.opentelemetry.io/otel/attribute",
}
