// Code generated by goexportdata. DO NOT EDIT.

package testifyexportdata

import (
	"embed"
	"io/fs"
)

//go:embed all:blobs
var blobs embed.FS

// FS holds the export data for Paths, ready to hand to a template's
// ExportData option.
var FS, _ = fs.Sub(blobs, "blobs")

// Paths are the import paths FS covers, for exportdata.Verify to check.
var Paths = []string{
	"github.com/stretchr/testify/assert",
	"github.com/stretchr/testify/require",
}
