/*
 * Moderne Proprietary. Only for use by Moderne customers under the terms of a commercial contract.
 */

package awssdkv2

import (
	"fmt"
	"path"
	"strings"

	"github.com/moderneinc/recipes-go/recipes/migration/awssdkv2/awsmanifest"
)

// v2 dropped the per-service iface packages, and the pattern they exist for —
// embedding the full interface so a mock only implements the methods it cares
// about — has no replacement in the narrow interfaces AWS recommends instead:
// an embedder overriding one of five methods would suddenly owe the other four.
// So the package is regenerated against the v2 client, which satisfies it by
// construction.
const (
	ifacePkgSuffix  = "iface"
	ifaceFileName   = "zz_awssdkv2_iface.go"
	ifaceHeader     = "// Code generated by MigrateAwsSdkGoToV2. DO NOT EDIT.\n\npackage %s\n\nimport (\n\t\"context\"\n\n\t\"%s\"\n)\n\n"
	ifaceDeclHeader = "// %s is the %s client's interface, regenerated against aws-sdk-go-v2.\n// Embedding it keeps a partial implementation partial, which is what the v1\n// package this replaces was for.\ntype %s interface {\n"
)

// ifaceParent is where the regenerated packages are written, relative to the
// module root. They cannot go under the v2 SDK's own path, since that module
// does not have them, so they live in the module being migrated.
const ifaceParent = "internal/awsiface"

// ifaceDir is the regenerated package's directory within the module.
func ifaceDir(service string) string {
	return path.Join(ifaceParent, service+ifacePkgSuffix)
}

// ifaceImportPath is what an importer of the regenerated package names.
func ifaceImportPath(module, service string) string {
	return module + "/" + ifaceDir(service)
}

// ifacePackageName returns the iface package a v1 import path names, and the
// service it belongs to: `.../service/s3/s3iface` is s3's.
func ifacePackageName(path string) (service, pkg string, ok bool) {
	rest, isService := strings.CutPrefix(path, v1ServicePkg)
	if !isService {
		return "", "", false
	}
	service, pkg, found := strings.Cut(rest, "/")
	if !found || pkg != service+ifacePkgSuffix {
		return "", "", false
	}
	return service, pkg, true
}

// ifaceTypeName is what v1 called the interface: the client type with API
// appended, as in S3API and CloudFormationAPI.
func ifaceTypeName(service string) (string, bool) {
	client, ok := awsmanifest.ClientType(service)
	if !ok {
		return "", false
	}
	return client + "API", true
}

// ifaceSource renders the replacement package for a service.
func ifaceSource(service string) (string, bool) {
	operations := awsmanifest.Operations(service)
	typeName, ok := ifaceTypeName(service)
	if !ok || len(operations) == 0 {
		return "", false
	}

	var b strings.Builder
	fmt.Fprintf(&b, ifaceHeader, service+ifacePkgSuffix, v2ServicePkg+service)
	fmt.Fprintf(&b, ifaceDeclHeader, typeName, service, typeName)
	for _, op := range operations {
		input, output, ok := awsmanifest.OperationShapes(service, op)
		if !ok {
			continue
		}
		fmt.Fprintf(&b, "\t%s(context.Context, *%s.%s, ...func(*%s.Options)) (*%s.%s, error)\n",
			op, service, input, service, service, output)
	}
	b.WriteString("}\n")
	return b.String(), true
}
