/*
 * Moderne Proprietary. Only for use by Moderne customers under the terms of a commercial contract.
 */

package awssdkv2

import (
	"github.com/moderneinc/recipes-go/recipes/internal/lstutil"
	"github.com/openrewrite/rewrite/rewrite-go/pkg/tree/golang"
	"github.com/openrewrite/rewrite/rewrite-go/pkg/tree/java"
	"github.com/openrewrite/rewrite/rewrite-go/pkg/visitor"
)

// v2 moved the instance metadata client into its own feature module and renamed
// both the package and the client type. Its methods changed shape too: each one
// takes a context and answers with an output struct, where v1 returned the value
// itself. Region is the one this recipe carries over, through a helper that
// keeps the v1 call site's shape.
const (
	v1Ec2Metadata     = v1Aws + "/ec2metadata"
	v2Imds            = v2Module + "/feature/ec2/imds"
	ec2MetadataClient = "EC2Metadata"

	imdsRegionHelper = "awsCompatIMDSRegion"
	imdsFileName     = "zz_awssdkv2_imds.go"
)

const imdsSource = `// Code generated by MigrateAwsSdkGoToV2. DO NOT EDIT.

package %s

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/feature/ec2/imds"
)

// awsCompatIMDSRegion stands in for aws-sdk-go v1's EC2Metadata.Region. v2 takes
// a context and answers with an output struct, so the call site keeps the shape
// it was written in by going through here.
func awsCompatIMDSRegion(ctx context.Context, c *imds.Client) (string, error) {
	out, err := c.GetRegion(ctx, &imds.GetRegionInput{})
	if err != nil {
		return "", err
	}
	return out.Region, nil
}
`

// imdsNames are the ec2metadata references the migration carries over.
var imdsNames = map[string]bool{"New": true, ec2MetadataClient: true}

// imdsMethods are the metadata client's methods with a v2 form this recipe
// writes.
var imdsMethods = map[string]bool{"Region": true}

// imdsVarScan records the names holding a metadata client, so its method calls
// are told apart from any other call in the file.
type imdsVarScan struct {
	visitor.GoVisitor
	scan *fileScan
}

func (v *imdsVarScan) VisitVariableDeclarations(vd *java.VariableDeclarations, p any) java.J {
	if v.scan.declaresMetadataClient(vd.TypeExpr) {
		for _, decl := range vd.Variables {
			if d := decl.Element; d != nil && d.Name != nil {
				v.scan.imdsVars[d.Name.Name] = true
			}
		}
	}
	return v.GoVisitor.VisitVariableDeclarations(vd, p)
}

func (v *imdsVarScan) VisitAssignment(a *java.Assignment, p any) java.J {
	if target, isIdent := a.Variable.(*java.Identifier); isIdent {
		if mi, isCall := a.Value.Element.(*java.MethodInvocation); isCall {
			if call, isMetadata := qualifiedCall(mi, v.scan.imdsPkg); isMetadata && call == "New" {
				v.scan.imdsVars[target.Name] = true
			}
		}
	}
	return v.GoVisitor.VisitAssignment(a, p)
}

// declaresMetadataClient reports whether a type expression is v1's
// *ec2metadata.EC2Metadata.
func (s *fileScan) declaresMetadataClient(expr java.Expression) bool {
	if s.imdsPkg == "" {
		return false
	}
	if ptr, isPointer := expr.(*golang.PointerType); isPointer {
		expr = ptr.Elem
	}
	fa, isField := expr.(*java.FieldAccess)
	if !isField {
		return false
	}
	name, isMetadata := qualifiedRef(fa, s.imdsPkg)
	return isMetadata && name == ec2MetadataClient
}

// imdsMethod names the metadata-client method a call invokes, when the receiver
// is one of the names the file holds a client in.
func (s *fileScan) imdsMethod(mi *java.MethodInvocation) (string, bool) {
	if s.imdsPkg == "" || mi.Name == nil || mi.Select == nil {
		return "", false
	}
	var recv string
	switch target := mi.Select.Element.(type) {
	case *java.Identifier:
		recv = target.Name
	case *java.FieldAccess:
		if target.Name.Element == nil {
			return "", false
		}
		recv = target.Name.Element.Name
	default:
		return "", false
	}
	if !s.imdsVars[recv] {
		return "", false
	}
	return mi.Name.Name, true
}

// imdsCall rewrites the metadata client's Region as the generated helper.
func (v *migrateVisitor) imdsCall(mi *java.MethodInvocation) (java.J, bool) {
	method, isMetadata := v.scan.imdsMethod(mi)
	if !isMetadata || method != "Region" || len(realArgs(mi)) != 0 {
		return nil, false
	}
	ctx := v.contextExpr()
	if ctx == nil {
		return nil, false
	}
	v.needsImdsHelper = true
	return &java.MethodInvocation{
		Prefix: mi.Prefix,
		Name:   &java.Identifier{Name: imdsRegionHelper},
		Arguments: java.Container[java.Expression]{Elements: []java.RightPadded[java.Expression]{
			{Element: lstutil.SetExprPrefix(ctx, java.EmptySpace)},
			{Element: lstutil.SetExprPrefix(mi.Select.Element, java.SingleSpace)},
		}},
		MethodType: lstutil.FuncType("", imdsRegionHelper, nil),
	}, true
}
