/*
 * Moderne Proprietary. Only for use by Moderne customers under the terms of a commercial contract.
 */

package awssdkv2

import (
	"github.com/moderneinc/recipes-go/recipes/internal/lstutil"
	"github.com/openrewrite/rewrite/rewrite-go/pkg/tree/java"
)

// A few of v1's service packages carried plain helper functions alongside the
// client. v2 dropped them, and they are small enough to carry over verbatim
// rather than leave a file behind for.
const (
	normalizeBucketLocation = "NormalizeBucketLocation"
	bucketLocationHelper    = "awsCompatBucketLocation"
	serviceHelperFileName   = "zz_awssdkv2_helpers.go"
)

const serviceHelperSource = `// Code generated by MigrateAwsSdkGoToV2. DO NOT EDIT.

package %s

// awsCompatBucketLocation is aws-sdk-go v1's s3.NormalizeBucketLocation, which
// v2 dropped. It reports the region a bucket's location constraint names, for
// the two values that are not region IDs.
func awsCompatBucketLocation(loc string) string {
	switch loc {
	case "":
		return "us-east-1"
	case "EU":
		return "eu-west-1"
	}
	return loc
}
`

// serviceHelpers are the v1 service functions a generated helper stands in for,
// keyed by the service that exported them.
var serviceHelpers = map[string]map[string]string{
	s3Service: {normalizeBucketLocation: bucketLocationHelper},
}

// serviceHelper names the generated function a v1 service helper becomes.
func (s *fileScan) serviceHelper(mi *java.MethodInvocation) (string, bool) {
	recv, isIdent := selectIdentifier(mi)
	if !isIdent || mi.Name == nil {
		return "", false
	}
	service, isService := s.services[recv.Name]
	if !isService {
		return "", false
	}
	helper, known := serviceHelpers[service][mi.Name.Name]
	return helper, known
}

// serviceHelperCall rewrites the call to name the generated function instead.
func (v *migrateVisitor) serviceHelperCall(mi *java.MethodInvocation) (java.J, bool) {
	helper, known := v.scan.serviceHelper(mi)
	if !known {
		return nil, false
	}
	v.needsServiceHelpers = true
	c := *mi
	c.Prefix = mi.Prefix
	c.Select = nil
	c.Name = &java.Identifier{Name: helper}
	c.MethodType = lstutil.FuncType("", helper, nil)
	return &c, true
}
