/*
 * Moderne Proprietary. Only for use by Moderne customers under the terms of a commercial contract.
 */

package awssdkv2

import (
	"github.com/moderneinc/recipes-go/recipes/internal/lstutil"
	"github.com/moderneinc/recipes-go/recipes/migration/awssdkv2/awsmanifest"
	"github.com/openrewrite/rewrite/rewrite-go/pkg/tree/golang"
	"github.com/openrewrite/rewrite/rewrite-go/pkg/tree/java"
)

// The helpers the migration leans on, and the file they are written to. v2
// holds a list of shapes by value where v1 held pointers, so rather than
// rewriting every producer and consumer of such a list, the list is converted
// where it crosses the API boundary and the surrounding code keeps its shape.
const (
	compatPtrs         = "awsCompatPtrs"
	compatVals         = "awsCompatVals"
	compatValsMap      = "awsCompatValsMap"
	compatPtrsMap      = "awsCompatPtrsMap"
	compatValsSliceMap = "awsCompatValsSliceMap"
	compatPtrsSliceMap = "awsCompatPtrsSliceMap"
	compatFileName     = "zz_awssdkv2_compat.go"
)

// compatSource is the helper file emitted once into each package that needs it.
const compatSource = `// Code generated by MigrateAwsSdkGoToV2. DO NOT EDIT.

package %s

// awsCompatPtrs views a value slice as the pointer slice aws-sdk-go v1
// modelled it as, aliasing the original so writes through an element still
// land. aws-sdk-go-v2 holds a list of shapes by value, and this keeps code
// written against v1 working unchanged.
func awsCompatPtrs[T any](vs []T) []*T {
	if vs == nil {
		return nil
	}
	ps := make([]*T, len(vs))
	for i := range vs {
		ps[i] = &vs[i]
	}
	return ps
}

// awsCompatVals is the inverse, for handing a v1-shaped list back to v2. A nil
// element has no representation in a value slice and becomes the zero value.
func awsCompatVals[T any](ps []*T) []T {
	if ps == nil {
		return nil
	}
	vs := make([]T, len(ps))
	for i, p := range ps {
		if p != nil {
			vs[i] = *p
		}
	}
	return vs
}

// awsCompatPtrsMap and awsCompatValsMap are the same pair for a map, which v2
// likewise holds by value.
func awsCompatPtrsMap[T any](m map[string]T) map[string]*T {
	if m == nil {
		return nil
	}
	out := make(map[string]*T, len(m))
	for k, v := range m {
		out[k] = &v
	}
	return out
}

func awsCompatValsMap[T any](m map[string]*T) map[string]T {
	if m == nil {
		return nil
	}
	out := make(map[string]T, len(m))
	for k, p := range m {
		if p != nil {
			out[k] = *p
		}
	}
	return out
}

// awsCompatPtrsSliceMap and awsCompatValsSliceMap are the same conversion one
// level deeper, for a map whose values are lists.
func awsCompatPtrsSliceMap[T any](m map[string][]T) map[string][]*T {
	if m == nil {
		return nil
	}
	out := make(map[string][]*T, len(m))
	for k, v := range m {
		out[k] = awsCompatPtrs(v)
	}
	return out
}

func awsCompatValsSliceMap[T any](m map[string][]*T) map[string][]T {
	if m == nil {
		return nil
	}
	out := make(map[string][]T, len(m))
	for k, v := range m {
		out[k] = awsCompatVals(v)
	}
	return out
}
`

// shapeRef names a modelled shape of a service.
type shapeRef struct {
	service string
	shape   string
}

// wrapCompat wraps expr in one of the helpers, keeping expr's own prefix on the
// call so the surrounding whitespace is unchanged.
func wrapCompat(helper string, expr java.Expression) java.Expression {
	return &java.MethodInvocation{
		Prefix: expr.GetPrefix(),
		Name:   &java.Identifier{Name: helper},
		Arguments: java.Container[java.Expression]{
			Elements: []java.RightPadded[java.Expression]{
				{Element: lstutil.SetExprPrefix(expr, java.EmptySpace)},
			},
		},
		MethodType: lstutil.FuncType("", helper, nil),
	}
}

// valueSliceRead reports whether fa reads a field v2 holds by value, returning
// the element shape when the elements are themselves shapes.
func (s *fileScan) valueSliceRead(fa *java.FieldAccess) (elem shapeRef, isRead bool) {
	if fa.Name.Element == nil {
		return shapeRef{}, false
	}
	target, ok := fa.Target.(*java.Identifier)
	if !ok {
		return shapeRef{}, false
	}
	owner, known := s.shapes[target.Name]
	if !known {
		return shapeRef{}, false
	}
	element := awsmanifest.ValueSliceElement(owner.service, owner.shape, fa.Name.Element.Name)
	if element == "" {
		return shapeRef{}, false
	}
	if element == "-" {
		return shapeRef{}, true
	}
	return shapeRef{service: owner.service, shape: element}, true
}

// valueMapRead reports whether fa reads a map field v2 holds by value, naming
// the helper that hands back the pointers v1 modelled it with.
func (s *fileScan) valueMapRead(fa *java.FieldAccess) (string, bool) {
	if fa.Name.Element == nil {
		return "", false
	}
	owner, known := s.receiverShape(fa.Target)
	if !known {
		return "", false
	}
	switch {
	case awsmanifest.IsMapOfValues(owner.service, owner.shape, fa.Name.Element.Name):
		return compatPtrsMap, true
	case awsmanifest.IsMapOfValueSlices(owner.service, owner.shape, fa.Name.Element.Name):
		return compatPtrsSliceMap, true
	}
	return "", false
}

// rangeElementShape names the shape a range over a value-slice field binds,
// which carries the inference one level deeper into a loop body.
func (s *fileScan) rangeElementShape(loop *java.ForEachLoop) (name string, ref shapeRef, ok bool) {
	assignment, isMulti := loop.Control.Variable.Element.(*golang.MultiAssignment)
	if !isMulti || len(assignment.Variables) != 2 {
		return "", shapeRef{}, false
	}
	value, isIdent := assignment.Variables[1].Element.(*java.Identifier)
	if !isIdent {
		return "", shapeRef{}, false
	}
	// The iterated expression was wrapped on the way in, so the field access
	// sits inside the helper call.
	iterated := loop.Control.Iterable.Element
	if mi, wrapped := iterated.(*java.MethodInvocation); wrapped && mi.Name != nil && mi.Name.Name == compatPtrs {
		args := realArgs(mi)
		if len(args) != 1 {
			return "", shapeRef{}, false
		}
		iterated = args[0]
	}
	// Ranging a local or a parameter declared as a slice of shapes binds them
	// just as directly as ranging a field of one does.
	if id, isIdent := iterated.(*java.Identifier); isIdent {
		if elem, held := s.sliceShapes[id.Name]; held {
			return value.Name, elem, true
		}
		return "", shapeRef{}, false
	}
	fa, isField := iterated.(*java.FieldAccess)
	if !isField {
		return "", shapeRef{}, false
	}
	elem, isSlice := s.valueSliceRead(fa)
	if !isSlice || elem.shape == "" {
		return "", shapeRef{}, false
	}
	return value.Name, elem, true
}
