/*
 * Moderne Proprietary. Only for use by Moderne customers under the terms of a commercial contract.
 */

package awssdkv2

import (
	"strings"

	"github.com/moderneinc/recipes-go/recipes/internal/lstutil"
	"github.com/moderneinc/recipes-go/recipes/migration/awssdkv2/awsmanifest"
	"github.com/openrewrite/rewrite/rewrite-go/pkg/tree/java"
)

// v1 gave a client a WaitUntilX method whose attempt count and delay were baked
// in. v2 makes the waiter a type built from the client, and takes the bound from
// the caller — a value the v1 call site never named, so it comes from a
// generated constant rather than a literal at each call.
const (
	waitDuration = "awsCompatWaitDuration"
	waitFileName = "zz_awssdkv2_wait.go"
)

const waitSource = `// Code generated by MigrateAwsSdkGoToV2. DO NOT EDIT.

package %s

import "time"

// awsCompatWaitDuration bounds a wait that aws-sdk-go v1 bounded with a
// per-waiter attempt count and delay. v2 takes the bound from the caller and
// there was nothing at the v1 call site to read it from, so this is a ceiling
// rather than the v1 default — review any wait that has to fail sooner.
const awsCompatWaitDuration = 5 * time.Minute
`

// waiterType names the v2 waiter a v1 WaitUntilX method became, and the service
// it belongs to. The manifest settles whether that type exists, since a waiter
// v1 had is not guaranteed a v2 counterpart.
func (s *fileScan) waiterType(mi *java.MethodInvocation) (service, waiter string, ok bool) {
	if mi.Name == nil || mi.Select == nil {
		return "", "", false
	}
	name := mi.Name.Name
	if !strings.HasPrefix(name, waiterPrefix) || name == waiterPrefix {
		return "", "", false
	}
	if len(realArgs(mi)) != 1 {
		return "", "", false
	}
	// The waiter is named for the shape the input is, not for an operation, so
	// the input the call takes settles the service without resolving the
	// receiver.
	service, _, isShape := s.inputShape(realArgs(mi)[0])
	if !isShape {
		return "", "", false
	}
	waiter = "New" + strings.TrimPrefix(name, waiterPrefix) + "Waiter"
	if awsmanifest.Place(service, waiter) != awsmanifest.InService {
		return "", "", false
	}
	return service, waiter, true
}

// waiterCall rewrites `svc.WaitUntilX(in)` as `<svc pkg>.NewXWaiter(svc).Wait(ctx, in, …)`.
func (v *migrateVisitor) waiterCall(mi *java.MethodInvocation) (java.J, bool) {
	service, waiter, ok := v.scan.waiterType(mi)
	if !ok {
		return nil, false
	}
	ctx := v.contextExpr()
	if ctx == nil {
		return nil, false
	}
	local := v.scan.qualifierFor(service)
	v.serviceUsed[service] = true
	v.needsWaitDuration = true

	construct := &java.MethodInvocation{
		Select:     &java.RightPadded[java.Expression]{Element: &java.Identifier{Name: local, Type: lstutil.NamedType(v2ServicePkg + service)}},
		Name:       &java.Identifier{Name: waiter},
		Arguments:  java.Container[java.Expression]{Elements: []java.RightPadded[java.Expression]{{Element: lstutil.SetExprPrefix(mi.Select.Element, java.EmptySpace)}}},
		MethodType: lstutil.FuncType(v2ServicePkg+service, waiter, nil),
	}
	return &java.MethodInvocation{
		Prefix: mi.Prefix,
		Select: &java.RightPadded[java.Expression]{Element: construct},
		Name:   &java.Identifier{Name: "Wait"},
		Arguments: java.Container[java.Expression]{Elements: []java.RightPadded[java.Expression]{
			{Element: lstutil.SetExprPrefix(ctx, java.EmptySpace)},
			{Element: lstutil.SetExprPrefix(realArgs(mi)[0], java.SingleSpace)},
			{Element: &java.Identifier{Prefix: java.SingleSpace, Name: waitDuration, Type: lstutil.NamedType("time.Duration")}},
		}},
		MethodType: lstutil.FuncType(v2ServicePkg+service+"."+waiter, "Wait", nil),
	}, true
}
