/*
 * Moderne Proprietary. Only for use by Moderne customers under the terms of a commercial contract.
 */

package ubermock_test

import (
	"testing"

	"github.com/moderneinc/recipes-go/recipes/migration/ubermock"
	"github.com/openrewrite/rewrite/rewrite-go/pkg/test"
)

func swapSpec() *test.RecipeSpec {
	return test.NewRecipeSpec().WithRecipe(&ubermock.SwapGolangMockImports{})
}

// The shape err0r500/go-realworld-clean uses throughout its uc package: a
// controller built from t, and expectations set through gomock matchers. The
// fork's API is identical, so only the import moves.
func TestSwapImportsInTestFile(t *testing.T) {
	swapSpec().RewriteRun(t,
		test.Golang(`
			package uc

			import (
				"errors"
				"testing"

				"github.com/golang/mock/gomock"
			)

			func TestUserEdit(t *testing.T) {
				mockCtrl := gomock.NewController(t)
				defer mockCtrl.Finish()

				i := newInteractor(mockCtrl)
				i.Logger.EXPECT().Log(gomock.Any()).AnyTimes()
				i.UserRW.EXPECT().GetByName(gomock.Any()).Return(nil, errors.New(""))
			}
		`, `
			package uc

			import (
				"errors"
				"testing"

				"go.uber.org/mock/gomock"
			)

			func TestUserEdit(t *testing.T) {
				mockCtrl := gomock.NewController(t)
				defer mockCtrl.Finish()

				i := newInteractor(mockCtrl)
				i.Logger.EXPECT().Log(gomock.Any()).AnyTimes()
				i.UserRW.EXPECT().GetByName(gomock.Any()).Return(nil, errors.New(""))
			}
		`),
	)
}

// appvia/terranetes-controller's tools.go pins the mockgen binary through blank
// imports; those travel with the module. The upstream file carries a
// `+"`//go:build tools`"+` constraint, dropped here so the parser admits it.
func TestSwapImportsToolsFile(t *testing.T) {
	swapSpec().RewriteRun(t,
		test.Golang(`
			package tools

			import (
				_ "github.com/golang/mock/gomock"
				_ "github.com/golang/mock/mockgen"
				_ "github.com/golang/mock/mockgen/model"
			)
		`, `
			package tools

			import (
				_ "go.uber.org/mock/gomock"
				_ "go.uber.org/mock/mockgen"
				_ "go.uber.org/mock/mockgen/model"
			)
		`),
	)
}

// A generated mock file imports gomock under an explicit alias, which the swap
// keeps.
func TestSwapImportsPreservesAlias(t *testing.T) {
	swapSpec().RewriteRun(t,
		test.Golang(`
			// Code generated by MockGen. DO NOT EDIT.

			package mocks

			import (
				reflect "reflect"

				gomock "github.com/golang/mock/gomock"
			)

			type MockEC2API struct {
				ctrl *gomock.Controller
			}

			func (m *MockEC2API) EXPECT() *gomock.Controller {
				m.ctrl.T.Helper()
				_ = reflect.TypeOf(m)
				return m.ctrl
			}
		`, `
			// Code generated by MockGen. DO NOT EDIT.

			package mocks

			import (
				reflect "reflect"

				gomock "go.uber.org/mock/gomock"
			)

			type MockEC2API struct {
				ctrl *gomock.Controller
			}

			func (m *MockEC2API) EXPECT() *gomock.Controller {
				m.ctrl.T.Helper()
				_ = reflect.TypeOf(m)
				return m.ctrl
			}
		`),
	)
}

// Already migrated: nothing to do.
func TestSwapImportsAlreadyOnFork(t *testing.T) {
	swapSpec().RewriteRun(t,
		test.Golang(`
			package uc

			import "go.uber.org/mock/gomock"

			func ctrlFor(t gomock.TestReporter) *gomock.Controller {
				return gomock.NewController(t)
			}
		`),
	)
}

// A file part-way through a hand migration imports both forks; swapping would
// duplicate the import, so it is left for review.
func TestSwapImportsBothForksImported(t *testing.T) {
	swapSpec().RewriteRun(t,
		test.Golang(`
			package uc

			import (
				oldmock "github.com/golang/mock/gomock"
				"go.uber.org/mock/gomock"
			)

			func ctrlFor(t gomock.TestReporter) *oldmock.Controller {
				return oldmock.NewController(t)
			}
		`),
	)
}
