/*
 * Moderne Proprietary. Only for use by Moderne customers under the terms of a commercial contract.
 */

package recipes

import (
	"github.com/moderneinc/recipes-go/code-quality/recipes/errorhandling"
	"github.com/moderneinc/recipes-go/code-quality/recipes/naming"
	"github.com/moderneinc/recipes-go/code-quality/recipes/performance"
	"github.com/moderneinc/recipes-go/code-quality/recipes/redundancy"
	"github.com/moderneinc/recipes-go/code-quality/recipes/simplification"
	"github.com/moderneinc/recipes-go/code-quality/recipes/style"
	"github.com/openrewrite/rewrite/pkg/recipe"
)

// Activate registers all Go code quality recipes with the given registry.
func Activate(r *recipe.Registry) {
	golang := recipe.CategoryDescriptor{DisplayName: "Go"}
	codeQuality := recipe.CategoryDescriptor{DisplayName: "Code quality", Description: "Recipes for improving Go code quality"}
	simplify := recipe.CategoryDescriptor{DisplayName: "Simplification", Description: "Simplify expressions and patterns"}
	redundant := recipe.CategoryDescriptor{DisplayName: "Redundancy", Description: "Remove redundant code"}

	// Simplification
	r.Register(&simplification.SimplifyBooleanExpression{}, golang, codeQuality, simplify)
	r.Register(&simplification.ReplaceTimeSinceWithSince{}, golang, codeQuality, simplify)
	r.Register(&simplification.ReplaceTimeUntilWithUntil{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyRedundantNilCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifySliceRange{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyFmtSprintf{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferBytesEqual{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferSortInts{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsHasPrefix{}, golang, codeQuality, simplify)
	r.Register(&simplification.UseStringsReplaceAll{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyRedundantTrimSpace{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsContainsOverCount{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferEmptyStringCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferLenCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferIoDiscard{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferIoNopCloser{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferIoReadAll{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsReadFile{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsWriteFile{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsMkdirTemp{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsCreateTemp{}, golang, codeQuality, simplify)
	r.Register(&simplification.FindChannelLenCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.FindRedundantRangeBlank{}, golang, codeQuality, simplify)
	r.Register(&simplification.FindSingleCaseSelect{}, golang, codeQuality, simplify)
	r.Register(&simplification.FindStdLog{}, golang, codeQuality, simplify)
	r.Register(&simplification.FindSwitchTrue{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferBytesHasPrefix{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferCopyString{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferErrorsIsForOsCheck{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferErrorsIsForPermission{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferFilepathClean{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferIoWriteString{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsReadDir{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferSlicesSort{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStrconvAtoi{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsBuilderWriteString{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsNewReader{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyTrimLeftNoop{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifySprintfConcat{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyDoubleNegation{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyBytesBufferRoundtrip{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyBytesSplitN{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyRedundantBytesTrimSpace{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifySplitN{}, golang, codeQuality, simplify)
	r.Register(&simplification.UseBytesReplaceAll{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferBytesContainsAny{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsContainsAny{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferStringsContainsRune{}, golang, codeQuality, simplify)
	r.Register(&simplification.UseHttpNewRequestWithContext{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferOsIsTimeout{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyErrorsIsNil{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferMinMaxBuiltin{}, golang, codeQuality, simplify)
	r.Register(&simplification.PreferBytesContainsRune{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyBytesEqualNil{}, golang, codeQuality, simplify)
	r.Register(&simplification.SimplifyIfReturnBool{}, golang, codeQuality, simplify)

	// Redundancy
	r.Register(&redundancy.RemoveRedundantReturn{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantBreak{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantBreakInSelect{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantSprintf{}, golang, codeQuality, redundant)
	r.Register(&redundancy.RemoveRedundantTypeConversion{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindBlankImport{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindEmptyDefault{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindEmptySwitch{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindNilCheckBeforeClose{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindRedundantElse{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindRedundantLenBeforeRange{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindSelfAssignment{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindUnreachableCode{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindConstantCondition{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindEmptyLoop{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindEmptyFmtSprintf{}, golang, codeQuality, redundant)
	r.Register(&redundancy.FindRedundantGoroutineClosure{}, golang, codeQuality, redundant)

	// Style
	styleCategory := recipe.CategoryDescriptor{DisplayName: "Style", Description: "Code style and conventions"}
	r.Register(&style.UseErrorsNewForSimpleErrors{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferStringsContains{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferBytesContains{}, golang, codeQuality, styleCategory)
	r.Register(&style.ExportedFuncShouldHaveComment{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferStringsEqualFold{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferStringsEqualFoldSingle{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferRegexpMustCompile{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindInitFunction{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindGlobalVar{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferRawStringForRegex{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindMathRand{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindDotImport{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferHexEncoding{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferStrconvQuote{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindBareReturnNilError{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindChannelClose{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindContextBackground{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindContextTodo{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindContextWithValue{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindDeeplyNestedBlock{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindDeprecatedAtomic{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindEmptyFunction{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindEmptyGoroutine{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindEmptyInterfaceParam{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindExecCommand{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindGoroutineClosure{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindHardcodedCredentials{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindHttpDefaultClient{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindHTTPListenAndServe{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindHttpRedirect{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindHttpListenAndServe{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindJsonNumber{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindJsonRawMessage{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindLargeInterface{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindLongFunction{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindMagicNumber{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindManyParams{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindManyReturns{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindDeeplyNestedErrorCheck{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindOsFileOpen{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindSkipWithoutReason{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindSQLStringConcat{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindTemplateExecute{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindTestFatal{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindTestMain{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindTimeSleep{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindTypeAssertionWithoutOk{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindUnbufferedChannel{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindUnsafeUsage{}, golang, codeQuality, styleCategory)
	r.Register(&style.PreferMakeForEmptyMap{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindHttpNewRequest{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindSqlOpen{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindYamlUnmarshal{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindFormatStringVariable{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindMapRangeClear{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindNestedGoroutine{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindDebugPrint{}, golang, codeQuality, styleCategory)
	r.Register(&style.FindSelectDefaultOnly{}, golang, codeQuality, styleCategory)

	// Error handling
	errCategory := recipe.CategoryDescriptor{DisplayName: "Error handling", Description: "Error handling best practices"}
	r.Register(&errorhandling.PreferErrorsIsOverEquality{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.CheckErrorReturn{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.WrapErrorWithContext{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindPanic{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindEmptyErrorCheck{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindCloseCall{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindDeferredClose{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindErrorStringComparison{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindErrorTypeAssertion{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindLogFatal{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindMultipleErrorWraps{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindOsExit{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindRecover{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorfWrapVerb{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.SimplifyRedundantErrorWrap{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindErrorsNew{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsContext{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsEOF{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.PreferErrorsIsForFieldAccess{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindErrorFmtSprint{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindContextErr{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindMustFunction{}, golang, codeQuality, errCategory)
	r.Register(&errorhandling.FindSwallowedError{}, golang, codeQuality, errCategory)

	// Performance
	perfCategory := recipe.CategoryDescriptor{DisplayName: "Performance", Description: "Performance optimizations"}
	r.Register(&performance.PreallocateSlice{}, golang, codeQuality, perfCategory)
	r.Register(&performance.PreferStrconvItoa{}, golang, codeQuality, perfCategory)
	r.Register(&performance.PreferStrconvFormatBool{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindDeferInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindJsonInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindMapAllocInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindNewInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindReflection{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindRegexInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindStringConcatInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.PreferBytesBufferString{}, golang, codeQuality, perfCategory)
	r.Register(&performance.SimplifySprintfChar{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindChannelCreateInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindFmtInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindGoroutineInLoop{}, golang, codeQuality, perfCategory)
	r.Register(&performance.FindLockInLoop{}, golang, codeQuality, perfCategory)

	// Naming
	namingCategory := recipe.CategoryDescriptor{DisplayName: "Naming", Description: "Naming conventions"}
	r.Register(&naming.FindMisnamedErrorVar{}, golang, codeQuality, namingCategory)
	r.Register(&naming.FindStutteringName{}, golang, codeQuality, namingCategory)
	r.Register(&naming.FindUnderscoredExportedName{}, golang, codeQuality, namingCategory)
	r.Register(&naming.FindAllCapsConstant{}, golang, codeQuality, namingCategory)
	r.Register(&naming.FindContextParamNotCtx{}, golang, codeQuality, namingCategory)
	r.Register(&naming.FindGetterPrefix{}, golang, codeQuality, namingCategory)
	r.Register(&naming.FindLongReceiverName{}, golang, codeQuality, namingCategory)
	r.Register(&naming.FindSingleLetterVar{}, golang, codeQuality, namingCategory)
}
